from typing import Optional
import numpy as np


def zeros(width: int, height: int, channels: int, pixelsPerBlock: int) -> BlockImage: ...
def load(filename: str) -> BlockImage: ...
class BlockImage:
    def __init__(self, arr: np.ndarray, pixelsPerBlock: int, blocksPerBlock = 2, colorThreshold: float = 0.0) -> None: ...
    def save(self, filename: str) -> None: ...     
    def to_numpy(self) -> np.ndarray: ...
    def resolution(self) -> int: ...
    def pixels_per_block(self) -> int: ...
    def blocks_per_block(self) -> int: ...