from typing import Optional
import numpy as np


def zeros(width: int, height: int, channels: int, pixels_per_block: int) -> bim: ...
def load(filename: str) -> bim: ...
class bim:
    class _bim_proxy:
        def __getitem__(self,i:int,j:int) -> bim: ...
        def __setitem__(self,pair:tuple,value:bim) -> None: ... 

    def __init__(self, arr: np.ndarray, pixels_per_block: int, blocks_per_block = 2, color_threshold: float = 0.0) -> None: ...
    def save(self, filename: str) -> None: ...     
    def numpy(self) -> np.ndarray: ...
    @property
    def resolution(self) -> int: ...
    @property
    def pixels_per_block(self) -> int: ...
    @property
    def blocks_per_block(self) -> int: ...
    @property
    def blocks(self) -> _bim_proxy: ...
    @property
    def canvas(self) -> np.ndarray: ...